### ISSUE TITLE
Whoops

### ISSUE THREAD

**Issue by sspencer10** [piplongrun/TrailerAddict.bundle#11]
All trailers say whoops video unavailable...

**Comment by vectronic** [comment]
First time I've installed and tried this. I get the little trailer icon when looking at the film info. But all trailers default after about 15 seconds to a 'Whoops' video.

I can't see any error logs in PMS logs.

I installed manually from trunk.

**Comment by piplongrun** [comment]
Yeah known issue :| Trailer Addict is actively blocking and changing stuff to prevent code like this agent from using their site content.

**Comment by sspencer10** [comment]
So is there a workaround or is this plugin dead?

**Comment by piplongrun** [comment]
> I can't see any error logs in PMS logs.

@vectronic It probably said "Regex failed" somewhere.

**Comment by sspencer10** [comment]
back to whoops :(

**Comment by piplongrun** [comment]
Back to working (v2.9)

**Comment by sspencer10** [comment]
yay!

**Comment by Catar1n0** [comment]
Love the plugin, start love watch trailer before see movie but back to whoops :(
maybe change website were get trailers?

**Comment by piplongrun** [comment]
> Update: Back to working again.

Thanks for the feedback! One of the servers used to get this all working somehow went down and didn't come back automatically. This _should_ be fixed now.
