### ISSUE TITLE
Even with 2.10 still not working

### ISSUE THREAD

**Issue by ekko20six** [piplongrun/TrailerAddict.bundle#12]
according to your comment as below, and being that my IP is banned and I can't access the site, with your proxy in place, Plex should still play the trailers correct? Or have I misunderstood?

The log is indicating to me that I am banned so is the plugin not using the proxy correctly?

Cheers for any help

[com.plexapp.agents.traileraddict.log](https://github.com/piplongrun/TrailerAddict.bundle/files/1504044/com.plexapp.agents.traileraddict.log)
--
If you can get to trailersddict website in browser you aren't blocked. If you can't then that's the issue.That's not really the case any more since version 2.3 where the caching proxy was introduced into the process. Problem is that certain users have been hammering my proxy so hard (thousands of requests in a short period) that the server is now blacklisted before it could build a decent cache.
--

ooo why did the font go all big here? I just copied it from an old issue. Sorry about that.

**Comment by piplongrun** [comment]
Some things have changed a bit. Explained here: http://forums.plex.tv/discussion/comment/1565680/#Comment_1565680
