### ISSUE TITLE
Trailer Addict downloading the same trailer instead of extras

### ISSUE THREAD

**Issue by Vader266** [piplongrun/TrailerAddict.bundle#13]
Hi there, 

As title - some of my library's trailers work ok but the majority just have a random trailer as their own. All the extras in multiple films in my library just play the same trailer.

It began as the Shawshank Redemption's trailer, but has since moved to the trailer for Midway. I have the Shawshank Redemption in my library but not Midway.

What is going on there? Find attached both the logs I could find (the log.1 with .txt appended so that I could upload it).

I am a Plex Pass user, I am using Plex Movie as a primary metadata agent with the following hierarchy:

Local Media Assets
Plex Movie*
Trailer Addict **
Fanart.tv (disabled)
CineMaterial (disabled)
OpenSubtitles.org (disabled)

---

* Within the settings are:
Localized titles (off)
Find trailers and extras automatically (on)
Skip extras which aren't trailers (off)
Use red band (restricted audiences) trailers when available (off)
Include extras with subtitles in Library language (off)

Cast List Source: The Movie Database
Ratings Source: Rotten Tomatoes
Plot Summary Source: The Movie Database
Country: United Kingdom

Use collection info from The Movie Database (off)
Prefer artwork based on library language (on)
Include adult content (off)
Send anonymous usage data to Plex (on)

---

** Settings within:
Add trailers (on)
Add feature trailers (on)
Add theatrical trailers (on)
Add featurettes (on)
Add interviews (off)
Add deleted scence (off)

---

[com.plexapp.agents.traileraddict.log](https://github.com/piplongrun/TrailerAddict.bundle/files/1670047/com.plexapp.agents.traileraddict.log)

[com.plexapp.agents.traileraddict.log.1.txt](https://github.com/piplongrun/TrailerAddict.bundle/files/1670048/com.plexapp.agents.traileraddict.log.1.txt)

**Comment by Vader266** [comment]
Update - it has now moved the Harry Potter & The Prisoner of Azkaban, which I have in my library but did not retrieve metadata for. Upon refreshing metadata, the Plex-retrieved trailer is correct and high-quality, but the Trailer Addict one is the low-quality version, albeit still correct.

Is this a very, very slow API call or something?

**Comment by piplongrun** [comment]
I introduced some caching to one of my own APIs that did not cache anything yet, because some endpoints are hit HARD by end users. Something went wrong with setting up the way the cache paths would be determined and all cache ended up being the same file that was served in the last 5 minutes (and refreshed for a different one, but served again for all requests for 5 minutes). This problem has been fixed and all stuff served from the cache should be unique for the request.

I just got home from my daytime job though to find, again, some errors in the server's log files. I'm investigating as we speak!

**Comment by piplongrun** [comment]
> the Plex-retrieved trailer is correct and high-quality, but the Trailer Addict one is the low-quality version

I looked this one up and yes the quality is pretty low on this one :( Unfortunately I have no control over the quality of the trailers on the source website.

**Comment by piplongrun** [comment]
No more errors in the last 24 hours server side. Is everything working as expected again for you?
