### ISSUE TITLE
Whoops Video Unavailable error

### ISSUE THREAD

**Issue by ltjdym** [piplongrun/TrailerAddict.bundle#14]
I keep getting this error on every plex movie I add. Is there a fix?

**Comment by ltjdym** [comment]
connecting to vpn that switched my ip address fixied. i guess my ip was banned,

**Comment by piplongrun** [comment]
Yes, that sounds like a ban :( It could be from before, when the agent made a lot more connections to their site. Recent versions of the agent only connect to their site when you watch a trailer (and never when indexing your library). Have you been watching _many, many_ trailers lately? Or do you have scripts running that use their site to grab and/or download trailers?

**Comment by ltjdym** [comment]
No I have not. Unless somehow Plex use it as a script when it refreshed all the metadata but I don't know how that would happen. Either way it looks like the problem is solved now I should have been using the VPN anyways thanks for the gentle shove.

**Comment by MrGiga** [comment]
I'm having this issue. Anyway to verify if my ip was banned? I have not been watching a lot of trailers.

**Comment by MrGiga** [comment]
Confirmed seemed like its an IP ban. For those who see this and have their plex on a NAS server and are unsure how to change your ip, do the following:
1. Turn off modem and unplug router from modem
2. Plug computer directly into modem and turn on modem
3. Verify that computer has a different ip address
4. Unplug computer from Modem, plug back into router (don't turn off modem)
5. Set mac address of your computer to the router (you won't have internet until you do this)

**Comment by piplongrun** [comment]
@MrGiga I don't know if that is going to work for a lot of people, I am pretty sure that this trick really depends on how your ISP gives out IP addresses.
