### ISSUE TITLE
Watch trailer without plex account login

### ISSUE THREAD

**Issue by Bizzmo** [piplongrun/TrailerAddict.bundle#15]
I have ended my Plex account since they started collecting user information. 

However, when using Plex on my Samsung TV, It seems that Traileraddict does not work unless I'm logged in with Plex account, even if it's on my LAN.

Is there a way to use this great plugin without a Plex account on a Samsung TV?

**Comment by piplongrun** [comment]
All I can say is that the TrailerAddict agent does require internet access, because all videos are streamed from the internet.

Do the trailers work from a different device (web client or Plex Media Player for example)?

**Comment by Bizzmo** [comment]
Yes it does. However if I try to start a trailer from plex on my samsung tv, I get an message that it requires the plex server to be connected to plex.tv (logged in) for it to work. Both devices are in the same LAN and subnet.
