### ISSUE TITLE
Store location?

### ISSUE THREAD

**Issue by IncognitoCore** [piplongrun/TrailerAddict.bundle#16]
It seems that it's storing the trailers in the Plex home directory, which is on a small drive. I'd like to know in which subdirectory the trailers are stored, if I can change the location and if there is a possibility to delete the trailers.

**Comment by piplongrun** [comment]
Trailer aren't stored anywhere locally. This agent just adds links to trailers and the trailers are streamed when played. Nothing is stored locally.
