### ISSUE TITLE
Not showing up in Agents?

### ISSUE THREAD

**Issue by 4jy** [piplongrun/TrailerAddict.bundle#17]
Hi, I have installed TrailerAddict.bundle into the Plug-Ins folder and i've restarted Plex however it doesn't show up under agents. Have I done something wrong?

**Comment by piplongrun** [comment]
If you install manually, make sure you:
- extract the .zip file;
- rename the resulting file so it ends in `.bundle` if it does not after extracting;
- place it in the [correct folder](https://support.plex.tv/articles/201106098-how-do-i-find-the-plug-ins-folder/).

Trailer Addict is a secondary agent, it will only show up under PlexMovie and The Movie Database.
