### ISSUE TITLE
Stuck transcoding in plex media player (windows) and never plays

### ISSUE THREAD

**Issue by liamreed** [piplongrun/TrailerAddict.bundle#19]
Been trying to get this working and trailers all show up in extras but trying to play them leads to it stalling at transcoding (8mbps 1080p) and doesn't work when i try to direct play them either.

**Comment by piplongrun** [comment]
For issues retrieving the correct file, replicate the issue, then have a look at `com.plexapp.agents.traileraddict.log`. For transcoding issues (which are _not_ agent issues but PMS issues) have a look at `Plex Media Server.log`.
