### ISSUE TITLE
TrailerAddict.bundle (Empty or non-existant file.) Exeption

### ISSUE THREAD

**Issue by dermitdemschaftanzt** [piplongrun/TrailerAddict.bundle#2]
at startup, the Media server throws the TrailerAddict.bundle (Empty or non-existant file.) exception

**Comment by piplongrun** [comment]
Sounds like a permission issue, but I don't know the OS your using for PMS. You may need to change the plugin bundle (and contents) to be owned by `plex:plex` (or the user/group your Plex Media Server is running on.)

`sudo chown plex:plex "/path/to/TrailerAddict.bundle"` (replace `/path/to/` with a real path of course.)
