### ISSUE TITLE
Refresh Metadata

### ISSUE THREAD

**Issue by BanditBanditBandit** [piplongrun/TrailerAddict.bundle#20]
I am having an issue with the metadata not being loaded for the entire library, it seems to stop after doing a handful of trailer downloads. Is there somewhere I can look at the logs of what it is doing? I have just decided to manually refresh the metadata on movies with missing trailers and so far its working on a one by one basis.

**Comment by piplongrun** [comment]
Please check the log file `com.plexapp.agents.traileraddict.log` (and `com.plexapp.agents.traileraddict.log.1`, `com.plexapp.agents.traileraddict.log.2`, etc if they exist) to see if it errors out somewhere. A couple of days ago there was an issue with a proxy server, that could have been a reason for not getting any data.
