### ISSUE TITLE
Force TrailerAddict to download only English-speaking Trailers

### ISSUE THREAD

**Issue by Swiss-Dude** [piplongrun/TrailerAddict.bundle#23]
Hello from Switzerland

I have recently started to use Plex (Plex Server running on a Windows 7 PC, in English, with settings as United States, with players on 3 PCs, 1 Mac, 4 iPhones and as an App on 3 Swisscom TV boxes).

I have added TrailerAddict as an Agent and configured it to add Trailers and Theatrical Trailers.

After a full refresh of my Movies, I notice that on some movies the International Trailer is the Japanese version instead of an English (US or UK) trailer.

Is there a way to force TrailerAddict to download only English-speaking trailers ?

Thanks in advance for any suggestions.

**Comment by piplongrun** [comment]
I might be able to filter out non English trailers in my code, but it will really depend on how the trailer(s) are listed. Can you give a few examples of movies that have non English trailers?

**Comment by Swiss-Dude** [comment]
Incredibles 2 International Trailer

**Comment by piplongrun** [comment]
> Incredibles 2 International Trailer

Unfortunately there is no way to detect that this is a non English ("wrong") version of the video. No indicators at all (also not on the details page)...

![trailer](https://user-images.githubusercontent.com/453429/45708297-4ce43680-bb81-11e8-8c07-7eb8fb0594c3.jpg)

**Comment by Swiss-Dude** [comment]
Bummer...  Thanks for looking into it.

**Comment by piplongrun** [comment]
The only option would be to create a "blacklist" with videos known to be incorrect. I am going to see if that is doable somehow.

**Comment by Swiss-Dude** [comment]
That would be a great solution.  There would have to be a system to add movies to the blacklist in some way as well.  I'll gladly Beta-test it if you find a way to do this.
