### ISSUE TITLE
A way to remove the 'Plex Pass' nag screen after playing a trailer?

### ISSUE THREAD

**Issue by voordev** [piplongrun/TrailerAddict.bundle#24]
Is there a way to remove the 'Plex Pass' nag screen after playing a trailer?
This screen is shown when you have no pass and click the trailer button in Plex.
The plugin works great , the trailers play perfect..

but this nag screen comes up after each trailer play and you cannot quickly step out of it you have to select 'not now' each time. 

Is there a way to bypass this?
Some flag in Plex one can set so it thinks it has Plex Pass or remove this nag screen?

I assume its inside the Plex binary, I assume its code signed.
But perhaps it possible to somehow change the Plex binary and re-sign it so it still runs on sinology?
Any thoughts on this? 
kind regards and many thanks for this great plugin

**Comment by piplongrun** [comment]
I do not feel comfortable discussing this issue and I don't feel it is something that should be discussed here, sorry.
