### ISSUE TITLE
Should trailer addict go back and get past stuff?

### ISSUE THREAD

**Issue by phunkb** [piplongrun/TrailerAddict.bundle#25]
Sorry to make an issue, couldn't really figure a way to contact. _Should_ the plugin work retrospectively? Or will it only do releases after I installed it?

**Comment by piplongrun** [comment]
It will grab trailers from the moment you activate the agent for newly added items in your library. If you want to have it add trailers to anything that is in your library already you can use the `Refresh All Metadata` option.
