### ISSUE TITLE
Not grabbing trailer, even though it exists!

### ISSUE THREAD

**Issue by samsepiol59** [piplongrun/TrailerAddict.bundle#26]
Hi, I hate opening this as a "issue" but it's the only way without writing to you directly on reddit!

Anyway, I just downloaded "Swimming with Men" and refreshed the metadata - but the trailer is not appearing! Even though it exists here https://www.youtube.com/watch?v=f495YKIfuaw

Is it because you don't grab trailers from YouTube? Is it because there's other words in the title of the video and that throws off the api/bot?

Thanks for the plugin, it's great!

**Comment by piplongrun** [comment]
> Is it because you don't grab trailers from YouTube?

That is correct. This agent grabs trailers from the Trailer Addict website only.
