### ISSUE TITLE
Trailer in French?

### ISSUE THREAD

**Issue by french-guy** [piplongrun/TrailerAddict.bundle#28]
Thanks for this add-on; very useful!
I'm wondering if there's way to get or select only french speaking trailer?
Thanks in advance,
Erik.

**Comment by piplongrun** [comment]
> I'm wondering if there's way to get or select only french speaking trailer?

Hi! Unfortunately the source website doesn't provide trailers in languages other than English :'(

**Comment by french-guy** [comment]
OK Thanks!
:-(
