### ISSUE TITLE
Working?

### ISSUE THREAD

**Issue by Salvationdk** [piplongrun/TrailerAddict.bundle#6]
I have done a full rescrape of all my movies, and i still dont get any trailers/extras to any movies. Is this addon still working? Maybe i have done somethinhg wrong.

**Comment by piplongrun** [comment]
Hi! You closed the issue, did you fix it somehow?

**Comment by Salvationdk** [comment]
found out were the trailer icon was

**Comment by tianmarin** [comment]
@Salvationdk where is it?

**Comment by piplongrun** [comment]
It is located here in the web:

![sc](https://user-images.githubusercontent.com/453429/31203301-ca2c110e-a966-11e7-9975-c9c90d42a70f.jpg)
