### ISSUE TITLE
API unavailable

### ISSUE THREAD

**Issue by heilerich** [piplongrun/TrailerAddict.bundle#7]
The plugin isn't working anymore and the log is filled with the following error

`ERROR (networking:219) - Error opening URL 'https://api.tadata.me/imdb2ta/v2/?imdb_id=#####'`

And indeed if I try to access the URL I'm getting a 404 error.

What's up with the API?

**Comment by piplongrun** [comment]
Oops! Slight misconfiguration on my side! Sorry about that, it has been fixed! Thanks for the report!
