### ISSUE TITLE
Trailer addict owner banned my ipaddress?

### ISSUE THREAD

**Issue by Gershy13** [piplongrun/TrailerAddict.bundle#9]
I was wondering why my trailers wouldnt work, so i went to the trailer addict website, and it says that the owner of the website has banned my ip address? I dont even use trailer addict. Only for plex.

Any idea of a way to fix this?

**Comment by piplongrun** [comment]
Known issue. It doesn't matter if you use the site or the agent, in the end they both hammer on the same website. More details in https://github.com/piplongrun/TrailerAddict.bundle/issues/8
